using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WinFormDevEx
{
    public partial class Form1: Form
    {
       DateTime  dCurrentDate=Convert.ToDateTime("05/27/2018");
       DateTime dLastDate;
        public Form1()
        {
            InitializeComponent();
            load_data(dCurrentDate);
            // This line of code is generated by Data Source Configuration Wizard
          //  entityServerModeSource1.QueryableSource = new WinFormDevEx.sampleEntities().TB_TEST;
           // this.gridView2.DetailHeight = 5;
            
        }

        private void Form1_Load(object sender, EventArgs e)
        {
           
            
        }

        //private void gridControl1_Click(object sender, EventArgs e)
        //{
        //   // this.textBox1.Text = this.gridView2.RowCount.ToString();
        //}

        //private void gridView2_Click(object sender, EventArgs e)
        //{
        //    //this.textBox1.Text = this.gridView2.RowCount.ToString();
        //}

        //private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        //{

        //}

        private void dateTimePicker1_ValueChanged(object sender, EventArgs e)
        {

            load_data(dateTimePicker1.Value) ;
        }

        public void load_data(DateTime str)
        {
            dCurrentDate = str;
            string  strdate = str.ToString("MM/dd/yyyy");// dateTimePicker1.Value.ToString("MM/dd/yyyy");
            DataSet dataset = new DataSet();
            //Please update the connection 
            string ConnString = "Data Source=SHAIF\\SQLEXPRESS;Initial Catalog=sample;Integrated Security=True";

            using (SqlConnection conn = new SqlConnection(ConnString))
            {
                //SqlDataAdapter adapter = new SqlDataAdapter();
                string queryString = "SELECT * FROM dbo.tb_test1 where FORMAT(Premiere_Date,'MM/dd/yyyy')=@pdate";
                SqlDataAdapter adapter = new SqlDataAdapter();//(queryString, conn);
                SqlCommand selectCMD = new SqlCommand(queryString, conn);
                adapter.SelectCommand = selectCMD;
                selectCMD.Parameters.Add("@pdate", SqlDbType.Date).Value = strdate;
                DataSet Data = new DataSet();
                adapter.Fill(Data, "Info");
                gridControl1.DataSource = Data.Tables[0];
                //if (Data.Tables[0].Rows.Count == 0 && dLastDate != dCurrentDate.AddDays(-1))
                //{
                //    dLastDate = dCurrentDate.AddDays(-1);
                //    load_data(dCurrentDate.AddDays(-1));
                //}

            }  
        }

        private void rowCountChanged(object sender, EventArgs e)
        {

           int topRowHandle = this.gridView2.GetVisibleRowHandle(this.gridView2.TopRowIndex);

           GridViewInfo viewInfo = this.gridView2.GetViewInfo() as GridViewInfo;

           int VisibleRows = viewInfo.RowsInfo.Count;
           

            if ((this.gridView2.TopRowIndex+VisibleRows) == (this.gridView2.RowCount -1) )
            {
               //  text = "End Reached";
                load_data(dCurrentDate.AddDays(1));
            }
            else if (this.gridView2.TopRowIndex ==0)
            {
                //  text = "Top Reached";
                load_data(dCurrentDate.AddDays(-1));
            }

            /*
           String text = this.gridView2.TopRowIndex.ToString() + "==" + this.gridView2.RowCount;
           */
           /*
            for (int visibleIndex = this.gridView2.TopRowIndex + 1; visibleIndex < this.gridView2.RowCount; visibleIndex++)
            {
                rowHandle = this.gridView2.GetVisibleRowHandle(visibleIndex);
                text = text+rowHandle.ToString()+"_"+(this.gridView2.IsRowVisible(rowHandle));
                if (this.gridView2.IsRowVisible(rowHandle) == RowVisibleState.Hidden)
                {
                      
                    break;
                }

               
            }
              this.textBox1.Text = text;
            **/
          // this.textBox1.Text = topRowHandle.ToString() + "_" + VisibleRows;
        }
    }
}
