//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormDevEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEST
    {
        public decimal ID { get; set; }
        public string ASSET_NAME { get; set; }
        public string ASSET_TYPE { get; set; }
        public Nullable<System.DateTime> Premiere_Date { get; set; }
    }
}
